### ISSUE TITLE
B100 Earthquake Detektor (sistem deteksi gempa)

### ISSUE THREAD

**Issue by ceefour** [lskk/earthquake-detector#1]

**Comment by kevprakoso** [comment]
[B100-TA-1617-01-069.docx](https://github.com/lskk/earthquake-detector/files/467979/B100-TA-1617-01-069.docx)
Ini draft B100 yang kami serahkan ke TU Prodi jum'at kemarin. Terima kasih

**Comment by ceefour** [comment]
Hendy butuh update B100
