### ISSUE TITLE
Visualization & Reporting Website

### ISSUE THREAD

**Issue by ceefour** [lskk/earthquake-detector#11]
* Web: [Django](http://djangoproject.com)
* Online course: https://www.udemy.com/try-django-v1-11-python-web-development/
* [Django-Bootstrap 4 integration](https://github.com/zostera/django-bootstrap4)
* Admin Template = [CoreUI React](http://coreui.io/react/)
* [Bootstrap 4](http://getbootstrap.com/)
* [React](https://facebook.github.io/react/)

**Comment by ridwansuhud** [comment]
Terima kasih Mas Hendy.


*Ridwan Suhud*
UPT Balai Informasi Teknologi - Lembaga Ilmu Pengetahuan Indonesia
Kompleks LIPI Gedung 40 Jl. Sangkuriang No. 10
Bandung 40135

**Comment by ceefour** [comment]
Implemented in https://github.com/lskk/ecnweb
